# Generated by Django 2.0.7 on 2018-08-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('admintype', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
    ]
