# Generated by Django 2.0.7 on 2018-08-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('entrance_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('c_id', models.IntegerField(blank=True, null=True)),
                ('s_id', models.IntegerField(blank=True, null=True)),
                ('a_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vote',
                'managed': False,
            },
        ),
    ]
